# Generated by Django 2.0.1 on 2019-05-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLogAlarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_name', models.CharField(help_text='自定义告警名称', max_length=128, null=True)),
                ('where_params', models.CharField(help_text='检索条件', max_length=256, null=True)),
                ('alarm_strategy', models.CharField(choices=[('average', '平均请求时间'), ('max', '最大请求时间'), ('cost_percent', '超过设定阀值的百分比')], help_text='策略', max_length=128, null=True)),
                ('time_ago', models.IntegerField(default=1, help_text='最近几分钟', null=True)),
                ('is_mail', models.BooleanField(default=0, help_text='发送email')),
                ('is_message', models.BooleanField(default=0, help_text='发送短信')),
                ('is_wechat', models.BooleanField(default=0, help_text='发送微信')),
                ('send_user_id', models.CharField(help_text='发送的user id 列表', max_length=256)),
                ('is_alarm', models.BooleanField(default=1, help_text='是否发送告警')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, help_text='更新时间')),
            ],
            options={
                'verbose_name': 'access log url 花费时间监控',
                'db_table': 'business_access_log_alarm',
            },
        ),
    ]
