# Generated by Django 2.0.1 on 2019-05-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20190513_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessalarmstrategy',
            name='strategy_id',
            field=models.IntegerField(help_text='strategy id', null=True, unique=True),
        ),
    ]
