# Generated by Django 2.0.1 on 2019-05-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_accessalarmstrategy_strategy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessalarmstrategy',
            name='alarm_strategy',
            field=models.CharField(choices=[('average', '平均请求时间'), ('max', '最大请求时间'), ('cost_percent', '超过设定阀值的百分比')], help_text='策略', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='accessalarmstrategy',
            name='where_condition',
            field=models.CharField(help_text='检索条件', max_length=1024, null=True),
        ),
    ]
