# Generated by Django 2.0.1 on 2019-05-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_auto_20190514_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessalarmstrategy',
            name='strategy_id',
        ),
        migrations.AddField(
            model_name='accessalarmstrategy',
            name='work_order',
            field=models.CharField(help_text='strategy id', max_length=128, null=True, unique=True),
        ),
    ]
