# Generated by Django 2.0.1 on 2019-05-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_auto_20190514_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessAlarmResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order', models.CharField(help_text='strategy uniq id', max_length=128, null=True, unique=True)),
                ('match_count', models.IntegerField(help_text='hit 的数目', null=True)),
                ('result_set', models.CharField(help_text='结果集', max_length=256, null=True)),
            ],
            options={
                'db_table': 'business_access_alarm_result',
            },
        ),
    ]
