# Generated by Django 2.0.1 on 2019-05-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_auto_20190514_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessalarmresult',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2019-05-14', help_text='创建时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accessalarmresult',
            name='match_count',
            field=models.IntegerField(default=0, help_text='hit 的数目'),
        ),
    ]
