# Generated by Django 2.0.1 on 2019-05-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_auto_20190514_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessalarmresult',
            name='match_count',
            field=models.IntegerField(default=0, help_text='hit 的数目', null=True),
        ),
    ]
