# Generated by Django 2.0.1 on 2019-05-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_auto_20190514_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessalarmresult',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='更新时间'),
        ),
    ]
