# Generated by Django 2.0.1 on 2019-05-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_accessalarmresult_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessalarmresult',
            name='latest_time',
            field=models.IntegerField(default=1, help_text='最近几分钟', null=True),
        ),
    ]
