# Generated by Django 2.0.1 on 2019-05-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_accessalarmresult_latest_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessalarmstrategy',
            name='op',
            field=models.CharField(default='>', help_text='比较符: >, >=, ==, <, <=', max_length=10, null=True),
        ),
    ]
