# Generated by Django 2.0.1 on 2019-05-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_accessalarmstrategy_op'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessalarmstrategy',
            name='cost',
            field=models.IntegerField(default=1, help_text='预设的秒数', null=True),
        ),
    ]
