# Generated by Django 2.0.1 on 2019-05-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_accessalarmstrategy_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessalarmresult',
            name='cost',
            field=models.IntegerField(default=1, help_text='预设的秒数', null=True),
        ),
    ]
