# Generated by Django 2.0.1 on 2019-05-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_accessalarmresult_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessalarmresult',
            name='cost',
            field=models.FloatField(default=1.0, help_text='预设的秒数', null=True),
        ),
        migrations.AlterField(
            model_name='accessalarmstrategy',
            name='cost',
            field=models.FloatField(default=1.0, help_text='预设的秒数', null=True),
        ),
    ]
