# Generated by Django 2.0.1 on 2019-05-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_auto_20190516_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessalarmresult',
            name='result_set',
            field=models.CharField(help_text='结果集', max_length=1024, null=True),
        ),
    ]
