# Generated by Django 2.0.1 on 2019-04-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AliyunEcs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(help_text='str; 主机名', max_length=100, null=True)),
                ('serial_number', models.CharField(help_text='str;', max_length=100, null=True)),
                ('cpu', models.IntegerField(help_text='int; cpu数量', null=True)),
                ('memory', models.IntegerField(help_text='int; memory MB', null=True)),
                ('os_type', models.CharField(help_text='str; 系统类型', max_length=20, null=True)),
                ('os_name', models.CharField(help_text='str; 系统名', max_length=50, null=True)),
                ('disk', models.CharField(help_text='str; 磁盘列表', max_length=500, null=True)),
                ('private_ip', models.CharField(help_text='str; 内网IP', max_length=200, null=True)),
                ('public_ip', models.CharField(help_text='str; 公网IP', max_length=100, null=True)),
                ('status', models.CharField(choices=[('Running', '运行中'), ('Starting', '启动中'), ('Stopping', '停止中'), ('Stopped', '已停止')], help_text='str; status', max_length=20, null=True)),
                ('environment', models.CharField(default='undefined', help_text='str; 环境名', max_length=50)),
                ('is_active', models.BooleanField(choices=[(0, '回收'), (1, '使用中')], default=1, help_text='int; 是否使用中')),
                ('updated', models.DateTimeField(auto_now=True, help_text='str; 更新时间')),
                ('ssh_port', models.IntegerField(default=38333, help_text='int; ssh 端口', null=True)),
                ('tag_id', models.IntegerField(help_text='str; 标签ID', null=True)),
                ('ac_key_id', models.IntegerField(help_text='str; access key id')),
                ('zone_id', models.CharField(help_text='str; 可用区', max_length=50, null=True)),
                ('region_id', models.CharField(help_text='str; 区域ID', max_length=50, null=True)),
                ('created', models.DateTimeField(help_text='str; 创建时间', null=True)),
                ('expired_time', models.DateTimeField(help_text='str; 过期时间', null=True)),
                ('instance_type', models.CharField(help_text='str; 实例类型', max_length=50, null=True)),
                ('instance_name', models.CharField(help_text='str; 实例名字', max_length=100, null=True)),
                ('instance_id', models.CharField(help_text='str; 实例ID', max_length=100, null=True)),
                ('instance_charge_type', models.CharField(choices=[('PrePaid', '包年包月'), ('PostPaid', '按量计费')], help_text='str; 付费方式', max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'cmdb 阿里云 ECS',
                'db_table': 'cmdb_cloud_aliyun_ecs',
            },
        ),
        migrations.CreateModel(
            name='AliyunKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.CharField(default=None, help_text='str; key名', max_length=150, null=True)),
                ('access_key', models.CharField(default=None, help_text='str; access key', max_length=100, null=True)),
                ('access_secret',
                 models.CharField(default=None, help_text='str; access secret', max_length=100, null=True)),
                ('region_id', models.CharField(default=None, help_text='str; 区域id', max_length=50, null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='更改时间')),
            ],
            options={
                'verbose_name': 'cmdb阿里云keys',
                'db_table': 'cmdb_cloud_aliyun_keys',
            },
        ),
    ]
