# Generated by Django 2.0.1 on 2019-04-21 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aliyunecs',
            name='tag_id',
        ),
    ]
