# Generated by Django 2.0.1 on 2019-04-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0003_auto_20190427_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliyunecs',
            name='ssh_ip',
            field=models.CharField(help_text='str; ssh ip', max_length=50, null=True),
        ),
    ]
