# Generated by Django 2.0.1 on 2019-05-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0004_aliyunecs_ssh_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliyunecs',
            name='swap',
            field=models.IntegerField(help_text='int; swap', null=True),
        ),
    ]
