# Generated by Django 2.0.1 on 2019-05-02 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0007_auto_20190501_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliyunecs',
            name='is_ansible',
            field=models.BooleanField(choices=[(0, '禁用'), (1, '激活')], default=1, help_text='int; 是否激活'),
        ),
    ]
