# Generated by Django 2.0.1 on 2019-05-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0008_aliyunecs_is_ansible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliyunecs',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='str; 更新时间', null=True),
        ),
    ]
