# Generated by Django 2.0.1 on 2019-06-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0009_auto_20190524_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliyunRDS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(help_text='instance id', max_length=128, null=True)),
                ('instance_desc', models.CharField(help_text='instance description', max_length=128, null=True)),
                ('status', models.CharField(default='Running', help_text='状态', max_length=50, null=True)),
                ('create_time', models.DateTimeField(help_text='创建时间', null=True)),
                ('expire_time', models.DateTimeField(help_text='过期时间', null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='更新时间', null=True)),
            ],
            options={
                'verbose_name': 'cmdb 阿里云 RDS',
                'db_table': 'cmdb_cloud_aliyun_rds',
            },
        ),
    ]
