# Generated by Django 2.0.1 on 2019-06-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0010_aliyunrds'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliyunrds',
            name='ac_key_id',
            field=models.IntegerField(help_text='int; access key id', null=True),
        ),
        migrations.AlterField(
            model_name='aliyunecs',
            name='ac_key_id',
            field=models.IntegerField(help_text='int; access key id', null=True),
        ),
    ]
