# Generated by Django 2.0.1 on 2019-06-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0012_aliyunrds_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliyunrds',
            name='is_active',
            field=models.BooleanField(default=1, help_text='是否在使用中'),
        ),
    ]
