# Generated by Django 2.0.1 on 2019-04-12 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionAll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField(help_text='组名ID', null=True)),
                ('page_permission', models.CharField(help_text='页面权限', max_length=500, null=True)),
            ],
            options={
                'db_table': 'permissions_all',
            },
        ),
    ]
