# Generated by Django 2.0.1 on 2019-04-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionall',
            name='page_permission',
            field=models.CharField(help_text='页面权限', max_length=1024, null=True),
        ),
    ]
