# Generated by Django 2.0.1 on 2019-04-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageinner',
            name='content',
            field=models.TextField(help_text='str; 内容'),
        ),
        migrations.AlterField(
            model_name='messageinner',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='str; 创建时间'),
        ),
        migrations.AlterField(
            model_name='messageinner',
            name='is_succeed',
            field=models.BooleanField(choices=[(0, '失败'), (1, '成功')], default=False, help_text='str; 是否发送成功'),
        ),
        migrations.AlterField(
            model_name='messageinner',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'trash'), (1, 'unread'), (2, 'read')], default=1, help_text='int; 状态: 0 trash, 1 unread, 2 read'),
        ),
        migrations.AlterField(
            model_name='messageinner',
            name='title',
            field=models.CharField(help_text='str; 标题', max_length=200),
        ),
        migrations.AlterField(
            model_name='messageinner',
            name='user_id',
            field=models.TextField(help_text='int; 接收用户的id'),
        ),
        migrations.AlterField(
            model_name='messagemail',
            name='content',
            field=models.TextField(help_text='str; 邮件内容'),
        ),
        migrations.AlterField(
            model_name='messagemail',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='str; 创建时间'),
        ),
        migrations.AlterField(
            model_name='messagemail',
            name='is_succeed',
            field=models.BooleanField(choices=[(0, '失败'), (1, '成功')], default=False, help_text='str; 是否发送成功'),
        ),
        migrations.AlterField(
            model_name='messagemail',
            name='receiver',
            field=models.TextField(help_text='st;: 目标邮箱'),
        ),
        migrations.AlterField(
            model_name='messagemail',
            name='title',
            field=models.CharField(help_text='str; 邮件标题', max_length=200),
        ),
        migrations.AlterField(
            model_name='messagemail',
            name='user_id',
            field=models.IntegerField(help_text='int; 用户id'),
        ),
    ]
