# Generated by Django 2.0.1 on 2019-04-17 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_pushmessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PushMessage',
            new_name='MessagePush',
        ),
        migrations.AlterModelTable(
            name='messagepush',
            table='message_push',
        ),
    ]
