# Generated by Django 2.0.1 on 2019-04-17 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_auto_20190417_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageinner',
            name='work_id',
            field=models.IntegerField(default=None, help_text='int; 工单号'),
        ),
        migrations.AddField(
            model_name='messagemail',
            name='work_id',
            field=models.IntegerField(default=None, help_text='int; 工单号'),
        ),
        migrations.AddField(
            model_name='messagepush',
            name='work_id',
            field=models.IntegerField(default=None, help_text='int; 工单号'),
        ),
    ]
