# Generated by Django 2.0.1 on 2019-04-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationGlobalLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(help_text='操作的uri', max_length=100)),
                ('method', models.CharField(help_text='http方法', max_length=10)),
                ('data', models.CharField(help_text='操作的数据', max_length=500)),
                ('description', models.CharField(help_text='操作描述', max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True, help_text='操作时间')),
                ('is_succeed', models.BooleanField(default=1, help_text='是否成功，0 失败，1 成功')),
            ],
            options={
                'db_table': 'operation_global_log',
            },
        ),
    ]
