# Generated by Django 2.0.1 on 2019-04-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationgloballog',
            name='user',
            field=models.CharField(default=1, help_text='用户名', max_length=150),
            preserve_default=False,
        ),
    ]
