# Generated by Django 2.0.1 on 2019-04-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_operationgloballog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationgloballog',
            name='data',
            field=models.TextField(help_text='操作的数据'),
        ),
    ]
