# Generated by Django 2.0.1 on 2019-04-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_auto_20190413_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationgloballog',
            name='description',
            field=models.CharField(help_text='操作描述', max_length=200),
        ),
    ]
