# Generated by Django 2.0.1 on 2019-04-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_auto_20190413_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationgloballog',
            name='is_succeed',
            field=models.BooleanField(choices=[(0, '失败'), (1, '成功')], default=1, help_text='是否成功，0 失败，1 成功'),
        ),
    ]
