# Generated by Django 2.0.1 on 2019-06-04 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb_common', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TagsAppRel',
        ),
    ]
