# Generated by Django 2.0.1 on 2019-05-23 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='domain', max_length=128, null=True)),
                ('status', models.CharField(help_text='状态', max_length=50, null=True)),
                ('create_time', models.DateTimeField(help_text='创建时间', null=True)),
                ('expire_time', models.DateTimeField(help_text='过期时间', null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='更新时间', null=True)),
                ('m_switch', models.BooleanField(default=1)),
            ],
            options={
                'verbose_name': '监控-Domain',
                'db_table': 'monitor_domain',
            },
        ),
        migrations.CreateModel(
            name='MonitorNAS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_id', models.CharField(help_text='system id', max_length=128, null=True)),
                ('package_id', models.CharField(help_text='package id', max_length=128, null=True)),
                ('desc', models.CharField(help_text='描述', max_length=128, null=True)),
                ('create_time', models.DateTimeField(help_text='创建时间', null=True)),
                ('expire_time', models.DateTimeField(help_text='过期时间', null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='更新时间', null=True)),
                ('m_switch', models.BooleanField(default=1)),
            ],
            options={
                'verbose_name': '监控-NAS',
                'db_table': 'monitor_nas',
            },
        ),
        migrations.CreateModel(
            name='MonitorRDS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(help_text='instance id', max_length=128, null=True)),
                ('instance_desc', models.CharField(help_text='instance description', max_length=128, null=True)),
                ('status', models.CharField(default='Running', help_text='状态', max_length=50, null=True)),
                ('create_time', models.DateTimeField(help_text='创建时间', null=True)),
                ('expire_time', models.DateTimeField(help_text='过期时间', null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='更新时间', null=True)),
                ('m_switch', models.BooleanField(default=1)),
            ],
            options={
                'verbose_name': '监控-RDS',
                'db_table': 'monitor_rds',
            },
        ),
        migrations.CreateModel(
            name='MonitorVPN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vpc_id', models.CharField(help_text='vpc id', max_length=128, null=True)),
                ('gateway_id', models.CharField(help_text='gateway id', max_length=128, null=True)),
                ('desc', models.CharField(help_text='描述', max_length=128, null=True)),
                ('status', models.CharField(help_text='状态', max_length=50, null=True)),
                ('create_time', models.DateTimeField(help_text='创建时间', null=True)),
                ('expire_time', models.DateTimeField(help_text='过期时间', null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='更新时间', null=True)),
                ('m_switch', models.BooleanField(default=1)),
            ],
            options={
                'verbose_name': '监控-VPN',
                'db_table': 'monitor_vpn',
            },
        ),
    ]
