# Generated by Django 2.0.1 on 2019-05-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorECS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(help_text='hostname', max_length=128, null=True)),
                ('server_id', models.CharField(help_text='server id', max_length=128, null=True)),
                ('status', models.CharField(help_text='status', max_length=50, null=True)),
                ('create_time', models.DateTimeField(help_text='创建时间', null=True)),
                ('expire_time', models.DateTimeField(help_text='过期时间', null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='更新时间', null=True)),
                ('m_switch', models.BooleanField(default=1)),
            ],
            options={
                'verbose_name': '监控-ECS',
                'db_table': 'monitor_ecs',
            },
        ),
    ]
