# Generated by Django 2.0.1 on 2019-05-24 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_monitorecs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitorvpn',
            old_name='gateway_id',
            new_name='vpn_id',
        ),
    ]
