# Generated by Django 2.0.1 on 2019-05-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20190524_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorThirdPartyStrategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitor_item', models.CharField(help_text='监控项目', max_length=50, null=True)),
                ('work_order', models.CharField(help_text='工单 唯一ID', max_length=128, null=True)),
                ('alert_number', models.IntegerField(help_text='告警数量', null=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='更新时间', null=True)),
                ('is_alarm', models.BooleanField(default=True, help_text='是否告警')),
            ],
            options={
                'verbose_name': '第三方监控策略',
                'db_table': 'monitor_tp_strategy',
            },
        ),
    ]
