# Generated by Django 2.0.1 on 2019-05-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_monitorthirdpartystrategy'),
    ]

    operations = [
        migrations.CreateModel(
            name='AModal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.IntegerField()),
                ('aa', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BModal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.IntegerField()),
                ('bb', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
