# Generated by Django 2.0.1 on 2019-05-24 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_amodal_bmodal'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='amodal',
            table='monitor_aa',
        ),
        migrations.AlterModelTable(
            name='bmodal',
            table='monitor_bb',
        ),
    ]
