# Generated by Django 2.0.1 on 2019-05-24 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_auto_20190524_1635'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AModal',
        ),
        migrations.DeleteModel(
            name='BModal',
        ),
    ]
