# Generated by Django 2.0.1 on 2019-05-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_auto_20190524_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitordomain',
            name='work_order',
            field=models.CharField(help_text='工单 唯一ID', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='monitorecs',
            name='work_order',
            field=models.CharField(help_text='工单 唯一ID', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='monitornas',
            name='work_order',
            field=models.CharField(help_text='工单 唯一ID', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='monitorrds',
            name='work_order',
            field=models.CharField(help_text='工单 唯一ID', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='monitorvpn',
            name='work_order',
            field=models.CharField(help_text='工单 唯一ID', max_length=128, null=True),
        ),
    ]
