# Generated by Django 2.0.1 on 2019-05-24 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_auto_20190524_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitordomain',
            old_name='m_switch',
            new_name='is_monitor',
        ),
        migrations.RenameField(
            model_name='monitorecs',
            old_name='m_switch',
            new_name='is_monitor',
        ),
        migrations.RenameField(
            model_name='monitornas',
            old_name='m_switch',
            new_name='is_monitor',
        ),
        migrations.RenameField(
            model_name='monitorrds',
            old_name='m_switch',
            new_name='is_monitor',
        ),
        migrations.RenameField(
            model_name='monitorvpn',
            old_name='m_switch',
            new_name='is_monitor',
        ),
    ]
