# Generated by Django 2.0.1 on 2019-05-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0012_auto_20190527_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorYueXin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order', models.CharField(help_text='工单 唯一ID', max_length=128, null=True)),
                ('compare_num', models.IntegerField(default=0, help_text='用于对比的数字，该数字通过不同类型的算法计算出来的')),
                ('updated', models.DateTimeField(auto_now=True, help_text='更新时间', null=True)),
                ('is_monitor', models.BooleanField(default=1)),
                ('req_code', models.CharField(help_text='状态', max_length=64, null=True)),
                ('req_message', models.CharField(help_text='查询信息', max_length=64, null=True)),
                ('balance', models.IntegerField(default=0, null=True)),
                ('username', models.CharField(help_text='用户名', max_length=32, null=True)),
            ],
            options={
                'verbose_name': '监控-YueXin',
                'db_table': 'monitor_yuexin',
            },
        ),
    ]
