# Generated by Django 2.0.1 on 2019-05-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0013_monitoryuexin'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorTencentSms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order', models.CharField(help_text='工单 唯一ID', max_length=128, null=True)),
                ('compare_num', models.IntegerField(default=0, help_text='用于对比的数字，该数字通过不同类型的算法计算出来的')),
                ('updated', models.DateTimeField(auto_now=True, help_text='更新时间', null=True)),
                ('is_monitor', models.BooleanField(default=1)),
                ('amount', models.IntegerField(default=0, help_text='总量', null=True)),
                ('used', models.IntegerField(default=0, help_text='使用量', null=True)),
                ('package_id', models.CharField(help_text='pkg_id', max_length=64, null=True, unique=True)),
            ],
            options={
                'verbose_name': '监控-腾讯-SMS',
                'db_table': 'monitor_tencent_sms',
            },
        ),
        migrations.CreateModel(
            name='MonitorWanWeiYiYuanBankIdentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order', models.CharField(help_text='工单 唯一ID', max_length=128, null=True)),
                ('compare_num', models.IntegerField(default=0, help_text='用于对比的数字，该数字通过不同类型的算法计算出来的')),
                ('updated', models.DateTimeField(auto_now=True, help_text='更新时间', null=True)),
                ('is_monitor', models.BooleanField(default=1)),
                ('remain_unit', models.IntegerField(default=0, help_text='剩余量', null=True)),
                ('total_unit', models.IntegerField(default=0, help_text='总量', null=True)),
                ('api_name', models.CharField(help_text='api name', max_length=64, null=True, unique=True)),
            ],
            options={
                'verbose_name': '监控-万维易源-银行卡身份证验证',
                'db_table': 'monitor_wanweiyiyuan_bankidentity',
            },
        ),
        migrations.CreateModel(
            name='MonitorXunChengEryaosu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order', models.CharField(help_text='工单 唯一ID', max_length=128, null=True)),
                ('compare_num', models.IntegerField(default=0, help_text='用于对比的数字，该数字通过不同类型的算法计算出来的')),
                ('updated', models.DateTimeField(auto_now=True, help_text='更新时间', null=True)),
                ('is_monitor', models.BooleanField(default=1)),
                ('number', models.IntegerField(default=0, help_text='剩余量', null=True)),
                ('key', models.CharField(help_text='key', max_length=64, null=True, unique=True)),
                ('name_desc', models.CharField(help_text='项目描述', max_length=64, null=True)),
                ('reason', models.CharField(help_text='返回信息', max_length=64, null=True)),
                ('error_code', models.SmallIntegerField(default=0, help_text='错误码')),
            ],
            options={
                'verbose_name': '监控-寻程-二要素验证',
                'db_table': 'monitor_xuncheng_eryaosu',
            },
        ),
        migrations.CreateModel(
            name='MonitorYueXinSms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order', models.CharField(help_text='工单 唯一ID', max_length=128, null=True)),
                ('compare_num', models.IntegerField(default=0, help_text='用于对比的数字，该数字通过不同类型的算法计算出来的')),
                ('updated', models.DateTimeField(auto_now=True, help_text='更新时间', null=True)),
                ('is_monitor', models.BooleanField(default=1)),
                ('req_code', models.CharField(help_text='状态', max_length=64, null=True)),
                ('req_message', models.CharField(help_text='查询信息', max_length=64, null=True)),
                ('balance', models.IntegerField(default=0, null=True)),
                ('username', models.CharField(help_text='用户名', max_length=32, null=True, unique=True)),
            ],
            options={
                'verbose_name': '监控-阅信-SMS',
                'db_table': 'monitor_yuexin_sms',
            },
        )
    ]
