# Generated by Django 2.0.1 on 2019-05-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0014_auto_20190529_1158'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonitorYueXin',
        ),
        migrations.RemoveField(
            model_name='monitordomain',
            name='work_order',
        ),
        migrations.RemoveField(
            model_name='monitorecs',
            name='work_order',
        ),
        migrations.RemoveField(
            model_name='monitornas',
            name='work_order',
        ),
        migrations.RemoveField(
            model_name='monitorrds',
            name='work_order',
        ),
        migrations.RemoveField(
            model_name='monitorvpn',
            name='work_order',
        ),
        migrations.AddField(
            model_name='monitorthirdpartystrategy',
            name='work_order',
            field=models.CharField(help_text='工单 唯一ID', max_length=128, null=True),
        ),
    ]
