# Generated by Django 2.0.1 on 2019-05-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0015_auto_20190529_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitortencentsms',
            name='current_alarm',
            field=models.BooleanField(default=0, help_text='是否处于告警状态'),
        ),
        migrations.AddField(
            model_name='monitorwanweiyiyuanbankidentity',
            name='current_alarm',
            field=models.BooleanField(default=0, help_text='是否处于告警状态'),
        ),
        migrations.AddField(
            model_name='monitorxunchengeryaosu',
            name='current_alarm',
            field=models.BooleanField(default=0, help_text='是否处于告警状态'),
        ),
        migrations.AddField(
            model_name='monitoryuexinsms',
            name='current_alarm',
            field=models.BooleanField(default=0, help_text='是否处于告警状态'),
        ),
        migrations.AlterField(
            model_name='monitortencentsms',
            name='compare_num',
            field=models.IntegerField(default=0, help_text='用于对比的数字，该数字通过不同类型的算法计算出来的, 如 "剩余量" 等'),
        ),
        migrations.AlterField(
            model_name='monitorwanweiyiyuanbankidentity',
            name='compare_num',
            field=models.IntegerField(default=0, help_text='用于对比的数字，该数字通过不同类型的算法计算出来的, 如 "剩余量" 等'),
        ),
        migrations.AlterField(
            model_name='monitorxunchengeryaosu',
            name='compare_num',
            field=models.IntegerField(default=0, help_text='用于对比的数字，该数字通过不同类型的算法计算出来的, 如 "剩余量" 等'),
        ),
        migrations.AlterField(
            model_name='monitoryuexinsms',
            name='compare_num',
            field=models.IntegerField(default=0, help_text='用于对比的数字，该数字通过不同类型的算法计算出来的, 如 "剩余量" 等'),
        ),
    ]
