# Generated by Django 2.0.1 on 2019-05-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0016_auto_20190529_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitordomain',
            name='current_alarm',
            field=models.BooleanField(default=0, help_text='是否处于告警状态'),
        ),
        migrations.AddField(
            model_name='monitorecs',
            name='current_alarm',
            field=models.BooleanField(default=0, help_text='是否处于告警状态'),
        ),
        migrations.AddField(
            model_name='monitornas',
            name='current_alarm',
            field=models.BooleanField(default=0, help_text='是否处于告警状态'),
        ),
        migrations.AddField(
            model_name='monitorrds',
            name='current_alarm',
            field=models.BooleanField(default=0, help_text='是否处于告警状态'),
        ),
        migrations.AddField(
            model_name='monitorvpn',
            name='current_alarm',
            field=models.BooleanField(default=0, help_text='是否处于告警状态'),
        ),
    ]
