# Generated by Django 2.0.1 on 2019-05-31 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0018_auto_20190531_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorthirdpartyjitterstrategy',
            name='hours_ago',
            field=models.IntegerField(default=1, help_text='对比第几个个小时前的数据'),
        ),
        migrations.AlterField(
            model_name='monitordomain',
            name='current_alarm',
            field=models.BooleanField(choices=[(1, '是'), (0, '否')], default=0, help_text='是否处于告警状态'),
        ),
        migrations.AlterField(
            model_name='monitordomain',
            name='is_monitor',
            field=models.BooleanField(choices=[(1, '是'), (0, '否')], default=1, help_text='1, 0; 是否监控'),
        ),
        migrations.AlterField(
            model_name='monitorecs',
            name='current_alarm',
            field=models.BooleanField(choices=[(1, '是'), (0, '否')], default=0, help_text='是否处于告警状态'),
        ),
        migrations.AlterField(
            model_name='monitorecs',
            name='is_monitor',
            field=models.BooleanField(choices=[(1, '是'), (0, '否')], default=1, help_text='1, 0; 是否监控'),
        ),
        migrations.AlterField(
            model_name='monitornas',
            name='current_alarm',
            field=models.BooleanField(choices=[(1, '是'), (0, '否')], default=0, help_text='是否处于告警状态'),
        ),
        migrations.AlterField(
            model_name='monitornas',
            name='is_monitor',
            field=models.BooleanField(choices=[(1, '是'), (0, '否')], default=1, help_text='1, 0; 是否监控'),
        ),
        migrations.AlterField(
            model_name='monitorrds',
            name='current_alarm',
            field=models.BooleanField(choices=[(1, '是'), (0, '否')], default=0, help_text='是否处于告警状态'),
        ),
        migrations.AlterField(
            model_name='monitorrds',
            name='is_monitor',
            field=models.BooleanField(choices=[(1, '是'), (0, '否')], default=1, help_text='1, 0; 是否监控'),
        ),
        migrations.AlterField(
            model_name='monitortencentsms',
            name='current_alarm',
            field=models.BooleanField(choices=[(1, '是'), (0, '否')], default=0, help_text='是否处于告警状态'),
        ),
        migrations.AlterField(
            model_name='monitortencentsms',
            name='is_monitor',
            field=models.BooleanField(choices=[(1, '是'), (0, '否')], default=1, help_text='1, 0; 是否监控'),
        ),
        migrations.AlterField(
            model_name='monitorvpn',
            name='current_alarm',
            field=models.BooleanField(choices=[(1, '是'), (0, '否')], default=0, help_text='是否处于告警状态'),
        ),
        migrations.AlterField(
            model_name='monitorvpn',
            name='is_monitor',
            field=models.BooleanField(choices=[(1, '是'), (0, '否')], default=1, help_text='1, 0; 是否监控'),
        ),
        migrations.AlterField(
            model_name='monitorwanweiyiyuanbankidentity',
            name='current_alarm',
            field=models.BooleanField(choices=[(1, '是'), (0, '否')], default=0, help_text='是否处于告警状态'),
        ),
        migrations.AlterField(
            model_name='monitorwanweiyiyuanbankidentity',
            name='is_monitor',
            field=models.BooleanField(choices=[(1, '是'), (0, '否')], default=1, help_text='1, 0; 是否监控'),
        ),
        migrations.AlterField(
            model_name='monitorxunchengeryaosu',
            name='current_alarm',
            field=models.BooleanField(choices=[(1, '是'), (0, '否')], default=0, help_text='是否处于告警状态'),
        ),
        migrations.AlterField(
            model_name='monitorxunchengeryaosu',
            name='is_monitor',
            field=models.BooleanField(choices=[(1, '是'), (0, '否')], default=1, help_text='1, 0; 是否监控'),
        ),
        migrations.AlterField(
            model_name='monitoryuexinsms',
            name='current_alarm',
            field=models.BooleanField(choices=[(1, '是'), (0, '否')], default=0, help_text='是否处于告警状态'),
        ),
        migrations.AlterField(
            model_name='monitoryuexinsms',
            name='is_monitor',
            field=models.BooleanField(choices=[(1, '是'), (0, '否')], default=1, help_text='1, 0; 是否监控'),
        ),
    ]
