# Generated by Django 2.0.1 on 2019-06-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0019_auto_20190531_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorTPStrategyItemRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_id', models.IntegerField(help_text='策略ID', null=True)),
                ('monitor_item_id', models.IntegerField(help_text='监控项目 ID', null=True)),
                ('monitor_item', models.CharField(help_text='监控项目', max_length=64)),
            ],
            options={
                'verbose_name': '监控-第三方策略—监控项目-告警关系',
                'db_table': 'monitor_tpstrategy_item_rel',
            },
        ),
    ]
