# Generated by Django 2.0.1 on 2019-06-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0020_monitortpstrategyitemrel'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitortpstrategyitemrel',
            name='current_alarm',
            field=models.BooleanField(choices=[(1, '告警'), (0, '恢复')], default=0, help_text='是在告警'),
        ),
    ]
