# Generated by Django 2.0.1 on 2019-06-09 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0021_monitortpstrategyitemrel_current_alarm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitordomain',
            name='current_alarm',
        ),
        migrations.RemoveField(
            model_name='monitorecs',
            name='current_alarm',
        ),
        migrations.RemoveField(
            model_name='monitornas',
            name='current_alarm',
        ),
        migrations.RemoveField(
            model_name='monitorrds',
            name='current_alarm',
        ),
        migrations.RemoveField(
            model_name='monitortencentsms',
            name='current_alarm',
        ),
        migrations.RemoveField(
            model_name='monitorvpn',
            name='current_alarm',
        ),
        migrations.RemoveField(
            model_name='monitorwanweiyiyuanbankidentity',
            name='current_alarm',
        ),
        migrations.RemoveField(
            model_name='monitorxunchengeryaosu',
            name='current_alarm',
        ),
        migrations.RemoveField(
            model_name='monitoryuexinsms',
            name='current_alarm',
        ),
    ]
