# Generated by Django 2.0.1 on 2019-04-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_setting', models.CharField(help_text='邮箱设置', max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='messageinner',
            name='is_succeed',
            field=models.BooleanField(choices=[(0, '失败'), (1, '成功')], default=False, help_text='是否发送成功'),
        ),
        migrations.AlterField(
            model_name='messagemail',
            name='is_succeed',
            field=models.BooleanField(choices=[(0, '失败'), (1, '成功')], default=False, help_text='是否发送成功'),
        ),
    ]
