# Generated by Django 2.0.1 on 2019-04-14 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20190414_2248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settingbase',
            options={'verbose_name': '基础设置'},
        ),
        migrations.AlterModelTable(
            name='settingbase',
            table='common_setting_base',
        ),
    ]
