# Generated by Django 2.0.1 on 2019-04-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20190414_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingbase',
            name='is_mail',
            field=models.BooleanField(default=True, help_text='是否启用mail'),
        ),
    ]
