# Generated by Django 2.0.1 on 2019-04-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_settingbase_is_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingbase',
            name='is_inner',
            field=models.BooleanField(default=True, help_text='是否启用站内信息'),
        ),
    ]
