# Generated by Django 2.0.1 on 2019-04-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_settingbase_is_inner'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageinner',
            name='status',
            field=models.SmallIntegerField(default=1, help_text='状态: 0 trash, 1 unread, 2 read'),
        ),
    ]
