# Generated by Django 2.0.1 on 2019-04-15 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_messageinner_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageInner',
        ),
        migrations.DeleteModel(
            name='MessageMail',
        ),
    ]
