# Generated by Django 2.0.1 on 2019-04-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20190415_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where', models.CharField(help_text='哪里的设置', max_length=50)),
                ('is_mail', models.BooleanField(default=True, help_text='是否启用mail')),
                ('is_inner', models.BooleanField(default=True, help_text='是否启用站内信息')),
                ('mail_setting', models.CharField(help_text='邮箱设置', max_length=500)),
            ],
            options={
                'verbose_name': '基础设置',
                'db_table': 'common_setting_conf',
            },
        ),
        migrations.DeleteModel(
            name='SettingBase',
        ),
    ]
