# Generated by Django 2.0.1 on 2019-04-17 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20190416_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settingconf',
            old_name='where',
            new_name='owner',
        ),
    ]
