# Generated by Django 2.0.1 on 2019-04-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20190417_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settingconf',
            name='mail_setting',
        ),
        migrations.AddField(
            model_name='settingconf',
            name='message_setting',
            field=models.CharField(default=1, help_text='邮箱设置', max_length=1024),
            preserve_default=False,
        ),
    ]
