# Generated by Django 2.0.1 on 2019-04-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_auto_20190417_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushMessageRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='str; 标题', max_length=100)),
                ('content', models.TextField(help_text='str; 消息内容')),
                ('user_id_list', models.CharField(help_text='str; 用户ID', max_length=500)),
                ('send_type_list', models.CharField(help_text='str; 发送消息类型', max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='str; 创建时间')),
            ],
            options={
                'verbose_name': '消息推送',
                'db_table': 'common_push_message_record',
            },
        ),
        migrations.AlterField(
            model_name='settingconf',
            name='message_setting',
            field=models.CharField(help_text='json; 消息设置', max_length=1024),
        ),
    ]
