# Generated by Django 2.0.1 on 2019-04-17 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_auto_20190417_1918'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PushMessageRecord',
            new_name='PushMessage',
        ),
        migrations.AlterModelTable(
            name='pushmessage',
            table='common_push_message',
        ),
    ]
