# Generated by Django 2.0.1 on 2019-04-17 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_auto_20190417_1919'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PushMessage',
        ),
    ]
