# Generated by Django 2.0.1 on 2019-04-20 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_delete_pushmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingconf',
            name='is_inner',
            field=models.BooleanField(default=True, help_text='int; 是否启用站内信息'),
        ),
        migrations.AlterField(
            model_name='settingconf',
            name='is_mail',
            field=models.BooleanField(default=True, help_text='int; 是否启用mail'),
        ),
        migrations.AlterField(
            model_name='settingconf',
            name='owner',
            field=models.CharField(help_text='str; 属主', max_length=50),
        ),
    ]
