# Generated by Django 2.0.1 on 2019-04-20 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_auto_20190420_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingconf',
            name='message_setting',
            field=models.CharField(help_text='json; 消息设置', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='settingconf',
            name='owner',
            field=models.CharField(help_text='str; 属主', max_length=50, null=True),
        ),
    ]
