# Generated by Django 2.0.1 on 2019-04-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_auto_20190420_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingconf',
            name='cmdb_setting',
            field=models.CharField(help_text='json; cmdb设置', max_length=1024, null=True),
        ),
    ]
