# Generated by Django 2.0.1 on 2019-05-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_settingconf_cmdb_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingconf',
            name='app_setting',
            field=models.CharField(help_text='json; app设置', max_length=1024, null=True),
        ),
    ]
