# Generated by Django 2.0.1 on 2019-05-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_settingconf_app_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsibleHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(blank=True, help_text='主机名', max_length=128, null=True)),
                ('group_name', models.CharField(help_text='组名', max_length=128, null=True)),
                ('host', models.CharField(help_text='ssh ip', max_length=20, null=True)),
                ('ansible_port', models.IntegerField(help_text='ansible port', null=True)),
                ('ansible_user', models.CharField(help_text='ansible user', max_length=128, null=True)),
                ('var_env', models.CharField(help_text='env', max_length=128, null=True)),
                ('var_domain', models.CharField(help_text='domain', max_length=128, null=True)),
                ('var_pub_ip', models.CharField(help_text='public ip', max_length=20, null=True)),
                ('var_tags', models.CharField(help_text='open-falcon tags', max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'ansible的inventory',
                'db_table': 'common_ansible_host',
            },
        ),
    ]
