# Generated by Django 2.0.1 on 2019-05-23 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_ansiblehost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ansiblehost',
            name='var_pub_ip',
        ),
        migrations.RemoveField(
            model_name='ansiblehost',
            name='var_tags',
        ),
    ]
