# Generated by Django 2.0.1 on 2019-07-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_auto_20190523_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingconf',
            name='code_publish_setting',
            field=models.CharField(default='[]', help_text='json; code publish设置', max_length=1024, null=True),
        ),
    ]
