# Generated by Django 2.0.1 on 2019-08-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_auto_20190731_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppALiveBrief',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(help_text='app name', max_length=128, null=True)),
                ('success_rate', models.IntegerField(default=0, help_text='成功率', null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='更新时间', null=True)),
            ],
            options={
                'db_table': 'common_app_alive_brief',
            },
        ),
        migrations.CreateModel(
            name='AppAliveStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(help_text='app name', max_length=128, null=True)),
                ('failed_point_amount', models.IntegerField(default=0, help_text='失败的点总数， 5分钟一个点')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True)),
            ],
            options={
                'db_table': 'common_app_alive_statistics',
            },
        ),
    ]
