# Generated by Django 2.0.1 on 2019-04-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NativeResourceHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(help_text='str; 主机名', max_length=100, null=True)),
                ('serial_number', models.CharField(help_text='str;', max_length=100, null=True)),
                ('idc', models.CharField(help_text='str; IDC', max_length=50, null=True)),
                ('cpu', models.IntegerField(help_text='int; cpu数量', null=True)),
                ('memory', models.IntegerField(help_text='int; memory MB', null=True)),
                ('os_type', models.CharField(help_text='str; 系统类型', max_length=20, null=True)),
                ('os_name', models.CharField(help_text='str; 系统名', max_length=50, null=True)),
                ('disk', models.CharField(help_text='str; 磁盘列表', max_length=500, null=True)),
                ('description', models.CharField(help_text='str; 描述', max_length=50, null=True)),
                ('private_ip', models.CharField(help_text='str; 内网IP', max_length=200, null=True)),
                ('public_ip', models.CharField(help_text='str; 公网IP', max_length=100, null=True)),
                ('status', models.CharField(choices=[('Running', '运行中'), ('Starting', '启动中'), ('Stopping', '停止中'), ('Stopped', '已停止')], help_text='str; status', max_length=20, null=True)),
                ('environment', models.CharField(default='undefined', help_text='str; 环境名', max_length=50)),
                ('is_active', models.BooleanField(choices=[(0, '回收'), (1, '使用中')], default=1, help_text='int; 是否使用中')),
                ('updated', models.DateTimeField(auto_now=True, help_text='str; 更新时间')),
                ('ssh_port', models.IntegerField(default=38333, help_text='int; ssh 端口', null=True)),
                ('tag_id', models.IntegerField(help_text='str; 标签ID', null=True)),
            ],
            options={
                'verbose_name': 'cmdb 本地服务器资源',
                'db_table': 'cmdb_native_resource_host',
            },
        ),
    ]
