# Generated by Django 2.0.1 on 2019-04-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('native', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_key', models.CharField(help_text='str; 标签名', max_length=100, null=True)),
                ('aliyun_ecs_id', models.IntegerField(help_text='int; aliyun_ecs_id', null=True)),
                ('native_host', models.IntegerField(help_text='int; native_host_id', null=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='str; 建立时间')),
            ],
            options={
                'verbose_name': 'cmdb 资源标签',
                'db_table': 'cmdb_resource_tags',
            },
        ),
    ]
