# Generated by Django 2.0.1 on 2019-04-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('native', '0002_resourcetags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceTagsRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.IntegerField(help_text='int; tag id', null=True)),
                ('aliyun_ecs_id', models.IntegerField(help_text='int; aliyun ecs id', null=True)),
                ('native_host_id', models.IntegerField(help_text='int; native host id', null=True)),
            ],
            options={
                'verbose_name': 'cmdb 资源标签关系',
                'db_table': 'cmdb_resource_tags_rel',
            },
        ),
        migrations.RemoveField(
            model_name='resourcetags',
            name='aliyun_ecs_id',
        ),
        migrations.RemoveField(
            model_name='resourcetags',
            name='native_host',
        ),
        migrations.AddField(
            model_name='resourcetags',
            name='tag_value',
            field=models.CharField(help_text='str; 标签值', max_length=200, null=True),
        ),
    ]
