# Generated by Django 2.0.1 on 2019-04-21 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('native', '0004_remove_nativeresourcehost_tag_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcetagsrelationship',
            old_name='aliyun_ecs_id',
            new_name='aliyun_ecs',
        ),
        migrations.RenameField(
            model_name='resourcetagsrelationship',
            old_name='native_host_id',
            new_name='native_host',
        ),
    ]
