# Generated by Django 2.0.1 on 2019-04-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('native', '0005_auto_20190421_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagsAliyunEcsRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.IntegerField(help_text='int; tag id', null=True)),
                ('target_id', models.IntegerField(help_text='int; aliyun ecs id', null=True)),
            ],
            options={
                'verbose_name': 'cmdb tag 与 阿里云 ecs 关系',
                'db_table': 'cmdb_tags_aliyunecs_rel',
            },
        ),
        migrations.CreateModel(
            name='TagsNativeHostRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.IntegerField(help_text='int; tag id', null=True)),
                ('target_id', models.IntegerField(help_text='int; native host id', null=True)),
            ],
            options={
                'verbose_name': 'cmdb tag 与 标签与本地服务器 关系',
                'db_table': 'cmdb_tags_nativehost_rel',
            },
        ),
        migrations.RenameModel(
            old_name='ResourceTags',
            new_name='Tags',
        ),
        migrations.DeleteModel(
            name='ResourceTagsRelationship',
        ),
        migrations.AlterModelTable(
            name='tags',
            table='cmdb_tags',
        ),
    ]
