# Generated by Django 2.0.1 on 2019-04-22 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('native', '0006_auto_20190422_1100'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NativeResourceHost',
            new_name='NativeHost',
        ),
        migrations.AlterModelTable(
            name='nativehost',
            table='cmdb_native_host',
        ),
    ]
