# Generated by Django 2.0.1 on 2019-04-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('native', '0007_auto_20190422_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagsAppRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.IntegerField(help_text='int; tag id', null=True)),
                ('target_id', models.IntegerField(help_text='int; app id', null=True)),
            ],
            options={
                'verbose_name': 'cmdb tag 与 标签与App关系',
                'db_table': 'cmdb_tags_app_rel',
            },
        ),
    ]
