# Generated by Django 2.0.1 on 2019-04-22 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('native', '0008_tagsapprel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tags',
        ),
        migrations.DeleteModel(
            name='TagsAliyunEcsRel',
        ),
        migrations.DeleteModel(
            name='TagsAppRel',
        ),
        migrations.DeleteModel(
            name='TagsNativeHostRel',
        ),
    ]
