# Generated by Django 2.0.1 on 2019-05-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('native', '0012_auto_20190501_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nativehost',
            name='hostname',
            field=models.CharField(help_text='str; 主机名', max_length=100, null=True),
        ),
    ]
