# Generated by Django 2.0.1 on 2019-05-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('native', '0015_auto_20190502_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nativehost',
            name='description',
            field=models.CharField(default='none', help_text='str; 描述', max_length=500, null=True),
        ),
    ]
