# Generated by Django 2.0.1 on 2019-05-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('native', '0016_auto_20190505_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nativehost',
            name='updated',
            field=models.DateTimeField(auto_now=True, default='2019-03-11 10:00:48.000000', help_text='str; 更新时间'),
            preserve_default=False,
        ),
    ]
