# Generated by Django 2.0.1 on 2019-07-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodePublishDockerOpts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docker_opts', models.TextField(null=True)),
            ],
            options={
                'db_table': 'cp_docker_opts',
            },
        ),
        migrations.CreateModel(
            name='CodePublishJarOpts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jar_opts', models.TextField(null=True)),
            ],
            options={
                'db_table': 'cp_jar_opts',
            },
        ),
        migrations.CreateModel(
            name='CodePublishJavaOpts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('java_opts', models.TextField(null=True)),
            ],
            options={
                'db_table': 'cp_java_opts',
            },
        ),
        migrations.CreateModel(
            name='CodePublishMainConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=64, null=True)),
                ('env', models.CharField(max_length=64, null=True)),
                ('publish_ip', models.CharField(help_text='list', max_length=256, null=True)),
                ('package_name', models.CharField(max_length=64, null=True)),
                ('java_opts', models.IntegerField()),
                ('jar_opts', models.IntegerField()),
                ('docker_opts', models.IntegerField()),
                ('steps', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now_add=True, help_text='更新时间', null=True)),
            ],
            options={
                'db_table': 'cp_main_conf',
            },
        ),
        migrations.CreateModel(
            name='CodePublishRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_conf_id', models.IntegerField()),
                ('sub_conf_id', models.IntegerField()),
                ('sub_type', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'cp_rel',
            },
        ),
        migrations.CreateModel(
            name='CodePublishStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=64, null=True)),
                ('env', models.CharField(max_length=32, null=True)),
                ('publish_version', models.CharField(max_length=64, null=True, unique=True)),
                ('publish_ip', models.CharField(max_length=32, null=True)),
                ('build_num', models.IntegerField()),
                ('action', models.CharField(help_text='[deploy|rollback]', max_length=32, null=True)),
                ('is_finished', models.SmallIntegerField(choices=[(0, 'unfinished'), (1, 'finished')], default=0)),
                ('stander_steps', models.CharField(max_length=256, null=True)),
                ('upload_steps', models.CharField(max_length=256, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, help_text='更新时间', null=True)),
                ('created', models.DateTimeField(auto_now=True, help_text='更新时间', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CodePublishSteps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deploy_steps', models.CharField(max_length=256, null=True)),
                ('rollback_steps', models.CharField(max_length=256, null=True)),
            ],
            options={
                'db_table': 'cp_steps',
            },
        ),
    ]
