# Generated by Django 2.0.1 on 2019-07-19 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_publish', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='codepublishstatus',
            table='cp_status',
        ),
    ]
