# Generated by Django 2.0.1 on 2019-07-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_publish', '0002_auto_20190719_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodePublishMvnOpts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mvn_opts', models.TextField(null=True)),
            ],
            options={
                'db_table': 'cp_mvn_opts',
            },
        ),
    ]
