# Generated by Django 2.0.1 on 2019-07-19 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_publish', '0004_codepublishmainconf_mvn_opts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codepublishmainconf',
            old_name='docker_opts',
            new_name='docker_opts_id',
        ),
        migrations.RenameField(
            model_name='codepublishmainconf',
            old_name='jar_opts',
            new_name='jar_opts_id',
        ),
        migrations.RenameField(
            model_name='codepublishmainconf',
            old_name='java_opts',
            new_name='java_opts_id',
        ),
        migrations.RenameField(
            model_name='codepublishmainconf',
            old_name='mvn_opts',
            new_name='mvn_opts_id',
        ),
        migrations.RenameField(
            model_name='codepublishmainconf',
            old_name='steps',
            new_name='steps_id',
        ),
    ]
