# Generated by Django 2.0.1 on 2019-07-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_publish', '0005_auto_20190719_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codepublishstatus',
            name='publish_version',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
