# Generated by Django 2.0.1 on 2019-07-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_publish', '0006_auto_20190719_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codepublishstatus',
            name='build_num',
            field=models.IntegerField(null=True),
        ),
    ]
