# Generated by Django 2.0.1 on 2019-07-22 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_publish', '0007_auto_20190719_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codepublishmainconf',
            old_name='package_name',
            new_name='pkg_name',
        ),
    ]
