# Generated by Django 2.0.1 on 2019-07-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_publish', '0008_auto_20190722_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodePublishDockerFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docker_file', models.TextField(null=True)),
            ],
            options={
                'db_table': 'cp_dockerfile',
            },
        ),
    ]
