# Generated by Django 2.0.1 on 2019-07-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_publish', '0009_codepublishdockerfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codepublishdockerfile',
            old_name='docker_file',
            new_name='c',
        ),
        migrations.AddField(
            model_name='codepublishmainconf',
            name='docker_file_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
