# Generated by Django 2.0.1 on 2019-07-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_publish', '0011_auto_20190722_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='codepublishmainconf',
            name='server_mode',
            field=models.CharField(default=1, help_text='[docker|tomcat|jar|tc2docker]', max_length=32),
            preserve_default=False,
        ),
    ]
