# Generated by Django 2.0.1 on 2019-07-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_publish', '0013_auto_20190724_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='codepublishmainconf',
            name='jenkins_project',
            field=models.CharField(help_text='jenkins project', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='codepublishmainconf',
            name='server_mode',
            field=models.CharField(help_text='[docker|tomcat|jar|tc2docker]', max_length=64, null=True),
        ),
    ]
