# Generated by Django 2.0.1 on 2019-07-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_publish', '0014_auto_20190724_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='codepublishdockerfile',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='codepublishdockeropts',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='codepublishjaropts',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='codepublishjavaopts',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='codepublishmvnopts',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='codepublishsteps',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='codepublishmainconf',
            name='docker_file_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='codepublishmainconf',
            name='docker_opts_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='codepublishmainconf',
            name='jar_opts_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='codepublishmainconf',
            name='java_opts_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='codepublishmainconf',
            name='mvn_opts_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='codepublishmainconf',
            name='steps_id',
            field=models.IntegerField(default=0),
        ),
    ]
