# Generated by Django 2.0.1 on 2019-07-25 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_publish', '0015_auto_20190724_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codepublishdockerfile',
            old_name='docker_file',
            new_name='dockerfile',
        ),
        migrations.RenameField(
            model_name='codepublishmainconf',
            old_name='docker_file_id',
            new_name='dockerfile_id',
        ),
    ]
