# Generated by Django 2.0.1 on 2019-07-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_publish', '0016_auto_20190725_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodePublishEnvMainConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env', models.CharField(max_length=128, null=True)),
            ],
            options={
                'db_table': 'cp_env_main_conf',
            },
        ),
        migrations.AlterField(
            model_name='codepublishmainconf',
            name='env',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
