# Generated by Django 2.0.1 on 2019-07-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_publish', '0017_auto_20190726_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codepublishenvmainconf',
            name='env',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
