# Generated by Django 2.0.1 on 2019-07-29 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_publish', '0018_auto_20190729_1055'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='codepublishmainconf',
            unique_together={('app_name', 'env')},
        ),
    ]
