# Generated by Django 2.0.1 on 2019-07-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_publish', '0019_auto_20190729_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodePublishWebSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_steps', models.CharField(help_text='部署步骤', max_length=256, null=True)),
            ],
            options={
                'db_table': 'cp_web_setting',
            },
        ),
        migrations.DeleteModel(
            name='CodePublishRel',
        ),
    ]
