# Generated by Django 2.0.1 on 2019-07-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_publish', '0020_auto_20190730_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codepublishwebsetting',
            name='publish_steps',
            field=models.CharField(default='[]', help_text='部署步骤', max_length=256, null=True),
        ),
    ]
