# Generated by Django 2.0.1 on 2019-08-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_publish', '0021_auto_20190731_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='codepublishmainconf',
            name='web_tag',
            field=models.CharField(help_text='web 平台标记是前端还是后端 [font-end|backend]', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='codepublishmainconf',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', null=True),
        ),
    ]
