# Generated by Django 2.0.1 on 2019-08-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_publish', '0022_auto_20190801_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodePublishWebControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=64, null=True)),
                ('env', models.CharField(max_length=32, null=True)),
                ('jenkins_job', models.CharField(help_text='jenkins project', max_length=64, null=True)),
                ('build_num', models.IntegerField(default=0)),
                ('publish_ip', models.CharField(max_length=32, null=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'null'), (1, 'success'), (2, 'failure'), (3, 'building'), (4, 'aborted')], default=0)),
                ('steps', models.IntegerField(default=0)),
                ('console_url', models.CharField(help_text='查看console log', max_length=256, null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='更新时间', null=True)),
            ],
            options={
                'db_table': 'cp_web_control',
            },
        ),
        migrations.AlterField(
            model_name='codepublishstatus',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='更新时间', null=True),
        ),
        migrations.AlterField(
            model_name='codepublishstatus',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', null=True),
        ),
    ]
