# Generated by Django 2.0.1 on 2019-08-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_publish', '0023_auto_20190805_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='codepublishwebcontrol',
            name='branch',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='codepublishwebcontrol',
            name='is_sync',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='codepublishwebcontrol',
            name='jenkins_params',
            field=models.CharField(help_text='jenkins params', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='codepublishwebcontrol',
            name='publish_version',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='codepublishwebcontrol',
            name='sync_env',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
