# Generated by Django 2.0.1 on 2019-08-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_publish', '0026_codepublishwebcontrol_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='codepublishwebcontrol',
            name='sync_ip',
            field=models.CharField(max_length=24, null=True),
        ),
    ]
