# Generated by Django 2.0.1 on 2019-08-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_publish', '0027_codepublishwebcontrol_sync_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='codepublishwebcontrol',
            name='stander_steps',
            field=models.CharField(default='[]', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='codepublishwebcontrol',
            name='upload_steps',
            field=models.CharField(default='[]', max_length=512, null=True),
        ),
    ]
