# Generated by Django 2.0.1 on 2019-08-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_publish', '0029_auto_20190810_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codepublishmainconf',
            name='publish_ip',
            field=models.CharField(default='[]', help_text='list', max_length=256, null=True),
        ),
    ]
