# Generated by Django 2.0.1 on 2019-08-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_publish', '0030_auto_20190812_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='codepublishwebcontrol',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='更新时间', null=True),
        ),
        migrations.AlterField(
            model_name='codepublishwebcontrol',
            name='branch',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='codepublishwebcontrol',
            name='has_been_published',
            field=models.CharField(default='[]', help_text='已经发布的IP; list', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='codepublishwebcontrol',
            name='publish_version',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='codepublishwebcontrol',
            name='sync_env',
            field=models.CharField(blank=True, default='[]', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='codepublishwebcontrol',
            name='sync_ip',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
