# Generated by Django 2.0.1 on 2019-08-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_publish', '0031_auto_20190815_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='codepublishsteps',
            name='deploy_sync_steps',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
