# Generated by Django 2.0.1 on 2019-08-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_publish', '0032_codepublishsteps_deploy_sync_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='codepublishmainconf',
            name='port',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='codepublishsteps',
            name='deploy_steps',
            field=models.CharField(default='[]', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='codepublishsteps',
            name='deploy_sync_steps',
            field=models.CharField(default='[]', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='codepublishsteps',
            name='rollback_steps',
            field=models.CharField(default='[]', max_length=256, null=True),
        ),
    ]
