# Generated by Django 2.0.1 on 2019-08-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_publish', '0033_auto_20190816_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodePublishLockEnv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock_grp_name', models.CharField(help_text='组名', max_length=128, null=True)),
                ('user_ids', models.CharField(default='[]', help_text='用户组', max_length=256, null=True)),
                ('lock_time', models.IntegerField(default=60, help_text='锁定时间')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True)),
                ('expired', models.DateTimeField(auto_now_add=True, help_text='过期时间', null=True)),
            ],
            options={
                'db_table': 'cp_lock_env',
            },
        ),
        migrations.CreateModel(
            name='CodePublishLockEnvApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(help_text='App Name', max_length=128, null=True)),
                ('env', models.CharField(help_text='env', max_length=64, null=True)),
                ('lock_grp_id', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'cp_lock_env_app',
            },
        ),
        migrations.AlterField(
            model_name='codepublishwebcontrol',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True),
        ),
    ]
