# Generated by Django 2.0.1 on 2019-08-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_publish', '0034_auto_20190820_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codepublishlockenvapp',
            name='app_name',
        ),
        migrations.AddField(
            model_name='codepublishlockenvapp',
            name='app_name_id',
            field=models.CharField(help_text='AppNameID from cp_main_conf', max_length=128, null=True),
        ),
    ]
