# Generated by Django 2.0.1 on 2019-08-20 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_publish', '0035_auto_20190820_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codepublishlockenvapp',
            name='env',
        ),
    ]
