# Generated by Django 2.0.1 on 2019-08-21 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_publish', '0036_remove_codepublishlockenvapp_env'),
    ]

    operations = [
        migrations.AddField(
            model_name='codepublishlockenv',
            name='env',
            field=models.CharField(help_text='env', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='codepublishlockenvapp',
            name='app_name_id',
            field=models.IntegerField(default=1, help_text='AppNameID from cp_main_conf'),
            preserve_default=False,
        ),
    ]
