# Generated by Django 2.0.1 on 2019-08-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_publish', '0038_auto_20190821_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='codepublishlockenv',
            name='creator',
            field=models.IntegerField(default=0, help_text='创建用户ID'),
        ),
    ]
