# Generated by Django 2.0.1 on 2019-08-22 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_publish', '0039_codepublishlockenv_creator'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='codepublishlockenv',
            unique_together={('creator', 'env')},
        ),
    ]
