# Generated by Django 2.0.1 on 2019-08-23 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_publish', '0042_codepublishlockenv_delay_lock_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codepublishlockenv',
            name='delay_lock_time',
        ),
    ]
