# Generated by Django 2.0.1 on 2019-08-24 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_publish', '0043_remove_codepublishlockenv_delay_lock_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodePublishGradleOpts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
                ('gradle_opts', models.TextField(null=True)),
            ],
            options={
                'db_table': 'cp_gradle_opts',
            },
        ),
    ]
