# Generated by Django 2.0.1 on 2019-08-24 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_publish', '0044_codepublishgradleopts'),
    ]

    operations = [
        migrations.AddField(
            model_name='codepublishmainconf',
            name='gradle_opts_id',
            field=models.IntegerField(default=0),
        ),
    ]
