# Generated by Django 2.0.1 on 2019-08-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_publish', '0045_codepublishmainconf_gradle_opts_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='codepublishwebcontrol',
            name='creator',
            field=models.CharField(help_text='发布者', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='codepublishwebcontrol',
            name='sync_env',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
