# Generated by Django 2.0.1 on 2019-08-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_publish', '0046_auto_20190828_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codepublishwebcontrol',
            name='creator',
            field=models.IntegerField(default=0, help_text='发布者'),
        ),
    ]
