# Generated by Django 2.0.1 on 2019-08-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_publish', '0048_auto_20190828_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodePublishWebControlSteps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(default=0, help_text='task id')),
                ('stander_steps', models.CharField(default='[]', help_text='stander steps', max_length=512, null=True)),
                ('upload_steps', models.CharField(default='[]', help_text='upload steps', max_length=512, null=True)),
            ],
            options={
                'db_table': 'cp_web_control_steps',
            },
        ),
        migrations.RemoveField(
            model_name='codepublishwebcontrol',
            name='stander_steps',
        ),
        migrations.RemoveField(
            model_name='codepublishwebcontrol',
            name='upload_steps',
        ),
    ]
