# Generated by Django 2.0.1 on 2019-05-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(help_text='app 名字', max_length=100, null=True)),
                ('port', models.IntegerField(help_text='启动端口', null=True)),
                ('description', models.CharField(help_text='描述', max_length=500, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, help_text='更新时间', null=True)),
                ('is_active', models.BooleanField(choices=[(1, '使用'), (0, '禁用')], default=1, help_text='是否使用中')),
                ('connector', models.CharField(default='[]', help_text='联系人id列表', max_length=200)),
                ('launch_cmd', models.CharField(help_text='启动命令', max_length=256)),
                ('internal_check_api', models.CharField(help_text='app 内部检查API', max_length=128)),
                ('external_check_api', models.CharField(help_text='app 外部检查API', max_length=128)),
            ],
            options={
                'verbose_name': 'app 详情',
                'db_table': 'app_detail',
            },
        ),
    ]
