# Generated by Django 2.0.1 on 2019-05-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdetail',
            name='chose_agent',
            field=models.CharField(choices=[('default', '阿里与生产(c-shenzhen)'), ('internal.ayg.gz', '内部广州爱员工')], help_text='选择发送api请求的agent', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appdetail',
            name='internal_check_api_env',
            field=models.CharField(help_text='app 内部检查API使用的环境', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='appdetail',
            name='is_external_check_api',
            field=models.BooleanField(default=0, help_text='是否发起外部api检查'),
        ),
        migrations.AddField(
            model_name='appdetail',
            name='is_internal_check_api',
            field=models.BooleanField(default=0, help_text='是否发起内部api检查'),
        ),
        migrations.AddField(
            model_name='appdetail',
            name='is_launch',
            field=models.BooleanField(default=0, help_text='是否可运行'),
        ),
        migrations.AddField(
            model_name='appdetail',
            name='is_publish',
            field=models.BooleanField(default=0, help_text='是否可发布'),
        ),
        migrations.AlterField(
            model_name='appdetail',
            name='external_check_api',
            field=models.CharField(help_text='app 外部检查API', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='appdetail',
            name='internal_check_api',
            field=models.CharField(help_text='app 内部检查API', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='appdetail',
            name='launch_cmd',
            field=models.CharField(help_text='启动命令', max_length=256, null=True),
        ),
    ]
