# Generated by Django 2.0.1 on 2019-05-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20190505_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppHostRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.IntegerField(help_text='app id', null=True)),
                ('host_id', models.IntegerField(help_text='host id', null=True)),
            ],
            options={
                'verbose_name': 'app host 关系',
                'db_table': 'app_host_rel',
            },
        ),
    ]
