# Generated by Django 2.0.1 on 2019-05-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_apphostrel'),
    ]

    operations = [
        migrations.AddField(
            model_name='apphostrel',
            name='owner',
            field=models.CharField(help_text='属于哪个资源表 [aliyun|native]', max_length=50, null=True),
        ),
    ]
