# Generated by Django 2.0.1 on 2019-05-08 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_apphostrel_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appdetail',
            name='launch_cmd',
        ),
    ]
