# Generated by Django 2.0.1 on 2019-05-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_remove_appdetail_launch_cmd'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConnectorRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.IntegerField(help_text='app id', null=True)),
                ('user_id', models.IntegerField(help_text='user id', null=True)),
            ],
            options={
                'verbose_name': 'app user 关系',
                'db_table': 'app_user_rel',
            },
        ),
        migrations.AlterField(
            model_name='appdetail',
            name='chose_agent',
            field=models.CharField(help_text='json; 选择发送api请求的agent\n                                    {"undefined": "default", "release": "default", "test92": "internal.ayg.gz"}', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appdetail',
            name='internal_check_api_env',
            field=models.CharField(help_text='json; app 内部检查API使用的环境 ["release", "test92"]', max_length=256, null=True),
        ),
    ]
