# Generated by Django 2.0.1 on 2019-05-09 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_auto_20190509_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appdetail',
            name='connector',
        ),
    ]
