# Generated by Django 2.0.1 on 2019-05-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_remove_appdetail_connector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdetail',
            name='chose_agent',
            field=models.CharField(help_text='json; 选择发送api请求的agent\n                                    {"undefined": "default", "release": "default", "test92": "internal.ayg.gz"}', max_length=512, null=True),
        ),
    ]
