# Generated by Django 2.0.1 on 2019-05-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_auto_20190509_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdetail',
            name='chose_agent',
            field=models.CharField(blank=True, help_text='str; 选择发送api请求的agent\n                                    {"undefined": "default", "release": "default", "test92": "internal.ayg.gz"}', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='appdetail',
            name='external_check_api',
            field=models.CharField(blank=True, help_text='app 外部检查API', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='appdetail',
            name='internal_check_api',
            field=models.CharField(blank=True, help_text='app 内部检查API', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='appdetail',
            name='internal_check_api_env',
            field=models.CharField(blank=True, help_text='json; app 内部检查API使用的环境 ["release", "test92"]', max_length=256, null=True),
        ),
    ]
