# Generated by Django 2.0.1 on 2019-06-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_appdetail_is_monitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdetail',
            name='app_name',
            field=models.CharField(help_text='app 名字', max_length=100, null=True, unique=True),
        ),
    ]
