# Generated by Django 2.0.1 on 2019-08-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_auto_20190607_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdetail',
            name='port',
            field=models.CharField(help_text='启动端口', max_length=32, null=True),
        ),
    ]
