# Generated by Django 2.0.1 on 2019-08-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_auto_20190819_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdetail',
            name='description',
            field=models.CharField(blank=True, help_text='描述', max_length=500, null=True),
        ),
    ]
