# Generated by Django 2.0.1 on 2019-08-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_auto_20190819_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdetail',
            name='is_monitor',
            field=models.BooleanField(default=0, help_text='是否APP Alive监控'),
        ),
    ]
