# Generated by Django 2.0.1 on 2019-04-11 14:42

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('users', '0002_auto_20190408_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
                ('description', models.CharField(help_text='str: 描述', max_length=100)),
            ],
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AlterField(
            model_name='usersaccount',
            name='department',
            field=models.CharField(help_text='str: 部门', max_length=100),
        ),
        migrations.AlterField(
            model_name='usersaccount',
            name='email',
            field=models.CharField(help_text='str: 邮箱', max_length=100),
        ),
        migrations.AlterField(
            model_name='usersaccount',
            name='position',
            field=models.CharField(help_text='str: 职位', max_length=100),
        ),
        migrations.AlterField(
            model_name='usersaccount',
            name='real_name',
            field=models.CharField(help_text='str: 真实姓名', max_length=100),
        ),
    ]
