# Generated by Django 2.0.1 on 2019-04-11 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190411_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersgroup',
            options={'verbose_name': '用户组'},
        ),
    ]
