# Generated by Django 2.0.1 on 2019-04-12 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190411_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersgroup',
            name='group_ptr',
        ),
        migrations.DeleteModel(
            name='UsersGroup',
        ),
    ]
