# Generated by Django 2.0.1 on 2019-05-11 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_usersaccount_ca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersaccount',
            name='ca',
        ),
    ]
